services:
  server:
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - db_name
      - db_user
      - db_admin
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - server_web
    restart: always
  
  db:
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - db_name
      - db_user
      - db_admin
    volumes:
      - databases:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_web
    restart: always

  web:
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - db_name
      - db_user
      - db_admin
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - server_web
      - db_web
    restart: always

volumes:
  databases:
    driver: local
  wordpress:
    driver: local

networks:
  db_web:
    driver: bridge
  server_web:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_admin:
    file: ../secrets/db_admin.txt
