services:
  nginx:
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    secrets:
      - nginx_key
      - nginx_cert
    ports:
      - "443:443"
    volumes:
      - /home/wkornato/data/wordpress:/var/www/html
    networks:
      - server_web
    restart: always
  
  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - db_name
      - db_user
      - db_admin
      - mariadb_server_cert
      - mariadb_server_key
      - ca_cert
    volumes:
      - /home/wkornato/data/databases:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_web
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_name
      - db_admin
      - mariadb_client_cert
      - mariadb_client_key
      - ca_cert
      - credentials
      - auth
      - redis_pass
    depends_on:
      - mariadb
    volumes:
      - /home/wkornato/data/wordpress:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - server_web
      - db_web
      - redis_web
    restart: always

  redis:
    build:
      context: ./requirements/redis
    secrets:
      - redis_pass
    ports:
      - "6379:6379"
    networks:
      - redis_web
    restart: always

  vsftpd:
    build:
      context: ./requirements/vsftpd
    env_file:
      - .env
    secrets:
      - ftp_credentials
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    volumes:
      - /home/wkornato/data/wordpress:/home/vsftpd
    restart: always

networks:
  db_web:
    driver: bridge
  server_web:
    driver: bridge
  redis_web:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_admin:
    file: ../secrets/db_admin.txt
  nginx_key:
    file: ../secrets/nginx-selfsigned.key
  nginx_cert:
    file: ../secrets/nginx-selfsigned.crt
  ca_cert:
    file: ../secrets/ca-cert.pem
  mariadb_server_cert:
    file: ../secrets/mariadb-server-cert.pem
  mariadb_server_key:
    file: ../secrets/mariadb-server-key.pem
  mariadb_client_cert:
    file: ../secrets/mariadb-client-cert.pem
  mariadb_client_key:
    file: ../secrets/mariadb-client-key.pem
  credentials:
    file: ../secrets/credentials.txt
  auth:
    file: ../secrets/auth.txt
  redis_pass:
    file: ../secrets/redis_pass.txt
  ftp_credentials:
    file: ../secrets/ftp_credentials.txt
