services:
  server:
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - server_web
    restart: always
  
  db:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 
    volumes:
      - ./requirements/mariadb/tools/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./requirements/mariadb/conf/my.cnf:/etc/my.cnf
      - ./requirements/mariadb/conf/mariadb-server.cnf:/etc/my.cnf.d/mariadb-server.cnf
      - databases:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_web
    restart: always

  web:
    build:
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - server_web
      - db_web
    restart: always

volumes:
  databases:
    driver: local
  wordpress:
    driver: local

networks:
  db_web:
    driver: bridge
  server_web:
    driver: bridge